NAME = CEDoom

DESCRIPTION = "a port of doom to a ti 84 plus ce calculater"

COMPRESSED = YES

COMPRESSED_MODE = zx0

CFLAGS = -Wall -Wextra -Oz -DF_CPU=48000000UL
CXXFLAGS = -Wall -Wextra -Oz

include $(shell cedev-config --makefile)